apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendpy
  namespace: practice-py
  labels:
    apipy: crm
spec:
  replicas: 2
  selector:
    matchLabels:
      apipy: crm
  template:
    metadata:
      labels:
        apipy: crm
    spec:
      containers:
      - name: reto2fastapivgc
        image: vgalindoc/reto2fastapivgc:3.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-crm
  namespace: practice-py
spec:
  selector:
    apipy: crm
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 7070